sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 6.0
services: docker
before_install:
 - cd Udemy-RestWithASP-NET5_Person
 - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag udemy-rest-with-asp-net5-db:$TRAVIS_JOB_ID $DOCKER_USERNAME/udemy-rest-with-asp-net5-db:$TRAVIS_JOB_ID;
    docker tag udemy-rest-with-asp-net5:$TRAVIS_JOB_ID $DOCKER_USERNAME/udemy-rest-with-asp-net5:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/udemy-rest-with-asp-net5:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/udemy-rest-with-asp-net5-db:$TRAVIS_JOB_ID;
  on:
    branch: main
notifications:
  email: false
    